// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpajgrngbnnoajdmqany.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwYWpncm5nYm5ub2FqZG1xYW55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMjA4NjksImV4cCI6MjA2NzY5Njg2OX0.k_8OTPYJHmM2Lt8GK-U5MuONxPgUYtQ_CTlg9TZvItM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});